# CMake generated Testfile for 
# Source directory: /Users/nishadelias/Documents/GitHub/CPU_SIM
# Build directory: /Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(rvc_expand_test "/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/rvc_expand_test")
set_tests_properties(rvc_expand_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;90;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(m_ext_syscall "/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/cpusim" "/Users/nishadelias/Documents/GitHub/CPU_SIM/instruction_memory/instMem-m-ext.txt")
set_tests_properties(m_ext_syscall PROPERTIES  PASS_REGULAR_EXPRESSION "Syscall exit code: 42" _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;91;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(golden_kernel_test "/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/golden_kernel_test" "/Users/nishadelias/Documents/GitHub/CPU_SIM/instruction_memory/instMem-m-ext.txt")
set_tests_properties(golden_kernel_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;93;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(load_use_test "/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/load_use_test" "/Users/nishadelias/Documents/GitHub/CPU_SIM/instruction_memory/instMem-load-use.txt")
set_tests_properties(load_use_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;95;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(forwarding_test "/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/forwarding_test" "/Users/nishadelias/Documents/GitHub/CPU_SIM/instruction_memory/instMem-forward.txt")
set_tests_properties(forwarding_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;97;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(fpu_decode_test "/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/fpu_decode_test")
set_tests_properties(fpu_decode_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;99;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(executable_mode_test "/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/executable_mode_test")
set_tests_properties(executable_mode_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;100;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(trap_test "/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/trap_test")
set_tests_properties(trap_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;101;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(mmu_test "/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/mmu_test")
set_tests_properties(mmu_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;102;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(hello_elf_test "bash" "-c" "\"/Users/nishadelias/Documents/GitHub/CPU_SIM/scripts/build_example_elf.sh\" &&        \"/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/hello_elf_test\" \"/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/hello.elf\"")
set_tests_properties(hello_elf_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;105;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(hello_elf_cpusim "bash" "-c" "\"/Users/nishadelias/Documents/GitHub/CPU_SIM/scripts/build_example_elf.sh\" &&        \"/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/cpusim\" \"/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/hello.elf\" --max-cycles 50000")
set_tests_properties(hello_elf_cpusim PROPERTIES  PASS_REGULAR_EXPRESSION "Syscall exit code: 42" _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;110;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(call_ret_elf_test "bash" "-c" "\"/Users/nishadelias/Documents/GitHub/CPU_SIM/scripts/build_example_elf.sh\" &&        \"/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/call_ret_elf_test\" \"/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/call_ret.elf\"")
set_tests_properties(call_ret_elf_test PROPERTIES  PASS_REGULAR_EXPRESSION "call_ret_elf_test ok" _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;116;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(fib_print_cpusim "bash" "-c" "\"/Users/nishadelias/Documents/GitHub/CPU_SIM/scripts/build_example_elf.sh\" &&        \"/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/cpusim\" \"/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/fib_print.elf\" --max-cycles 200000")
set_tests_properties(fib_print_cpusim PROPERTIES  PASS_REGULAR_EXPRESSION "Syscall exit code: 0" _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;122;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(count_primes_cpusim "bash" "-c" "\"/Users/nishadelias/Documents/GitHub/CPU_SIM/scripts/build_example_elf.sh\" &&        \"/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/cpusim\" \"/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/count_primes.elf\" --max-cycles 300000")
set_tests_properties(count_primes_cpusim PROPERTIES  PASS_REGULAR_EXPRESSION "Syscall exit code: 0" _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;128;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
add_test(bench_smoke_test "bash" "-c" "\"/Users/nishadelias/Documents/GitHub/CPU_SIM/scripts/build_example_elf.sh\" &&        \"/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/cpusim\" \"/Users/nishadelias/Documents/GitHub/CPU_SIM/build-gui/hello.elf\" --bench --json --max-cycles 50000")
set_tests_properties(bench_smoke_test PROPERTIES  PASS_REGULAR_EXPRESSION "\"syscall_exit_code\":42" _BACKTRACE_TRIPLES "/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;134;add_test;/Users/nishadelias/Documents/GitHub/CPU_SIM/CMakeLists.txt;0;")
